version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DEV_MODE=${DEV_MODE}
      - API_KEY=${API_KEY}
      - FROM_NUMBER=${FROM_NUMBER}
      - SMS_API_URL=${SMS_API_URL}
      - PROJECT_ID=${PROJECT_ID}
      - CREDENTIALS_PATH=/secrets/service-account.json
    volumes:
      #- .:/app
      - ./secrets/service-account.json:/secrets/service-account.json:ro
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: